version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: trading_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: tradingpass
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: trading_clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9900:9000"
    volumes:
      - chdata:/var/lib/clickhouse

  app:
    build: .
    container_name: trading_app
    depends_on:
      - postgres
      - clickhouse
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: trading
      POSTGRES_USERNAME: trading
      POSTGRES_PASSWORD: tradingpass
      POSTGRES_SSLMODE: disable

      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEBUG: "false"

    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
  chdata:
