-- Seed exchanges data
INSERT INTO exchanges (exchange_id, name, base_url, ticker_endpoint, symbols_endpoint, rate_limit_per_minute, weight, symbol_format, quote_currencies, is_active) VALUES
('binance', 'Binance', 'https://api.binance.com', '/api/v3/ticker/24hr', '/api/v3/exchangeInfo', 1200, 0.15, 'BTCUSDT', ARRAY['USDT', 'USDC', 'BUSD', 'BTC', 'ETH', 'BNB'], true),
('coinbase', 'Coinbase', 'https://api.exchange.coinbase.com', '/products', '/products', 600, 0.12, 'BTC-USD', ARRAY['USD', 'USDT', 'EUR', 'GBP', 'BTC', 'ETH'], true),
('kraken', 'Kraken', 'https://api.kraken.com', '/0/public/Ticker', '/0/public/AssetPairs', 60, 0.10, 'XXBTZUSD', ARRAY['USD', 'EUR', 'GBP', 'CAD', 'JPY', 'USDT', 'USDC'], true),
('okx', 'OKX', 'https://www.okx.com', '/api/v5/market/tickers?instType=SPOT', '/api/v5/public/instruments?instType=SPOT', 600, 0.08, 'BTC-USDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH', 'OKB'], true),
('bybit', 'Bybit', 'https://api.bybit.com', '/v5/market/tickers?category=spot', '/v5/market/instruments-info?category=spot', 600, 0.07, 'BTCUSDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH'], true),
('bitget', 'Bitget', 'https://api.bitget.com', '/api/v2/spot/market/tickers', '/api/v2/spot/public/symbols', 600, 0.06, 'BTCUSDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH'], true),
('gateio', 'Gate.io', 'https://api.gateio.ws', '/api/v4/spot/tickers', '/api/v4/spot/currency_pairs', 900, 0.05, 'BTC_USDT', ARRAY['USDT', 'BTC', 'ETH', 'USD'], true),
('huobi', 'Huobi', 'https://api.huobi.pro', '/market/tickers', '/v1/common/symbols', 100, 0.04, 'btcusdt', ARRAY['USDT', 'HUSD', 'BTC', 'ETH'], true),
('kucoin', 'KuCoin', 'https://api.kucoin.com', '/api/v1/market/allTickers', '/api/v2/symbols', 600, 0.05, 'BTC-USDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH', 'KCS'], true),
('cryptocom', 'Crypto.com', 'https://api.crypto.com', '/v2/public/get-ticker', '/v2/public/get-instruments', 100, 0.03, 'BTC_USDT', ARRAY['USDT', 'USDC', 'USD', 'CRO'], true),
('mexc', 'MEXC', 'https://api.mexc.com', '/api/v3/ticker/24hr', '/api/v3/exchangeInfo', 600, 0.03, 'BTCUSDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH'], true),
('bitfinex', 'Bitfinex', 'https://api-pub.bitfinex.com', '/v2/tickers?symbols=ALL', '/v1/symbols', 90, 0.03, 'tBTCUSD', ARRAY['USD', 'USDT', 'EUR', 'GBP', 'JPY', 'BTC', 'ETH'], true),
('gemini', 'Gemini', 'https://api.gemini.com', '/v1/pricefeed', '/v1/symbols', 120, 0.02, 'btcusd', ARRAY['USD', 'USDT', 'DAI', 'BTC', 'ETH'], true),
('bitstamp', 'Bitstamp', 'https://www.bitstamp.net', '/api/v2/ticker', '/api/v2/trading-pairs-info', 600, 0.02, 'btcusd', ARRAY['USD', 'EUR', 'GBP', 'USDT', 'USDC'], true),
('upbit', 'Upbit', 'https://api.upbit.com', '/v1/ticker', '/v1/market/all', 600, 0.02, 'KRW-BTC', ARRAY['KRW', 'USDT', 'BTC'], true),
('bithumb', 'Bithumb', 'https://api.bithumb.com', '/public/ticker/ALL_KRW', '/public/ticker/ALL_KRW', 90, 0.01, 'BTC_KRW', ARRAY['KRW'], true),
('lbank', 'LBank', 'https://api.lbkex.com', '/v2/ticker/24hr.do?symbol=all', '/v2/accuracy.do', 200, 0.01, 'btc_usdt', ARRAY['USDT', 'BTC', 'ETH'], true),
('bitmart', 'BitMart', 'https://api-cloud.bitmart.com', '/spot/v2/ticker', '/spot/v1/symbols', 600, 0.01, 'BTC_USDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH'], true),
('whitebit', 'WhiteBIT', 'https://whitebit.com', '/api/v4/public/ticker', '/api/v4/public/markets', 600, 0.01, 'BTC_USDT', ARRAY['USDT', 'USDC', 'USD', 'EUR', 'BTC', 'ETH'], true),
('coinex', 'CoinEx', 'https://api.coinex.com', '/v1/market/ticker/all', '/v1/market/info', 600, 0.01, 'BTCUSDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH', 'CET'], true),
('poloniex', 'Poloniex', 'https://api.poloniex.com', '/markets/ticker24h', '/markets', 200, 0.01, 'BTC_USDT', ARRAY['USDT', 'USDC', 'BTC', 'ETH', 'TRX'], true),
('bitflyer', 'bitFlyer', 'https://api.bitflyer.com', '/v1/ticker', '/v1/markets', 500, 0.01, 'BTC_JPY', ARRAY['JPY', 'USD', 'EUR'], true),
('coinone', 'Coinone', 'https://api.coinone.co.kr', '/ticker?currency=all', '/ticker?currency=all', 90, 0.01, 'btc', ARRAY['KRW'], true),
('wazirx', 'WazirX', 'https://api.wazirx.com', '/sapi/v1/tickers/24hr', '/sapi/v1/exchangeInfo', 600, 0.01, 'btcusdt', ARRAY['USDT', 'INR', 'WRX'], true),
('coindcx', 'CoinDCX', 'https://api.coindcx.com', '/exchange/ticker', '/exchange/v1/markets', 200, 0.01, 'BTCUSDT', ARRAY['USDT', 'INR', 'BTC', 'ETH'], true),
('btse', 'BTSE', 'https://api.btse.com', '/spot/v3/market_summary', '/spot/v3/market_summary', 150, 0.01, 'BTC-USD', ARRAY['USD', 'USDT', 'EUR', 'GBP', 'JPY'], true),
('deepcoin', 'Deepcoin', 'https://api.deepcoin.com', '/deepcoin/market/tickers', '/deepcoin/market/symbols', 200, 0.01, 'BTC-USDT', ARRAY['USDT', 'USDC'], true),
('pionex', 'Pionex', 'https://api.pionex.com', '/api/v1/market/tickers', '/api/v1/common/symbols', 600, 0.01, 'BTC_USDT', ARRAY['USDT', 'BTC', 'ETH'], true),
('toobit', 'Toobit', 'https://api.toobit.com', '/quote/v1/ticker/24hr', '/quote/v1/ticker/24hr', 200, 0.01, 'BTCUSDT', ARRAY['USDT'], true),
('hashkey', 'HashKey Global', 'https://api-pro.hashkey.com', '/api/v1/market/tickers', '/api/v1/exchangeInfo', 200, 0.01, 'BTCUSDT', ARRAY['USDT', 'USD', 'HKD'], true)
ON CONFLICT (exchange_id) DO UPDATE SET
    name = EXCLUDED.name,
    base_url = EXCLUDED.base_url,
    ticker_endpoint = EXCLUDED.ticker_endpoint,
    symbols_endpoint = EXCLUDED.symbols_endpoint,
    rate_limit_per_minute = EXCLUDED.rate_limit_per_minute,
    weight = EXCLUDED.weight,
    symbol_format = EXCLUDED.symbol_format,
    quote_currencies = EXCLUDED.quote_currencies,
    updated_at = NOW();