-- Remove newly discovered tokens
-- Note: This will only work if there are no foreign key constraints

DELETE FROM tokens WHERE symbol IN (
'XYO', 'XEN', 'SLAY', 'PUMPBTC', 'XRD', 'XFI', 'XVG', 'XDG', 'RUJI', 'DOGE3S',
'XDB', 'BTCZ', 'BASEDPEPE', 'XNO', 'XRP3S', 'CYC', 'A_', 'BTC3L', 'XNY', 'BTC3S',
'GEEK', 'NFT3L', 'DG', 'SLP', 'MDX', 'CPC', 'HOT', 'UXUY', 'KPAD', 'BTG',
'XRD5L', 'TOTO', 'OVC', 'LIMO', 'COCBULL', 'SHV', 'CMN', 'CRAZYPEPE', 'METAAPE', 'OKMUSDT',
'KELO', 'MEME3L', 'HABIBI', 'FET', 'DYDX5L', 'BTCE3L', 'CVIP', 'FLOKI5L', 'DOGE5L', 'BTCE3S',
'DODO3L', 'WIFA', 'SHYFT', 'YSP', 'SOP3L', 'SOP3S', 'XPG', 'OPUL', 'DOGE5S', 'SHI',
'PEPE3L', 'DYMM', 'PSG', 'POOH', 'SDN', 'GMM', 'MEME3S', 'NAX', 'FLOKI5S', 'XRP5L',
'WAXP', 'CELO', 'DYDX5S', 'LEVER', 'NRFP', 'PEPE3S', 'ARB3L', 'B', 'XRP5S', 'XRD5S',
'AAPL3L', 'ARB3S', 'KPOP', 'SUPE', 'DODO3S', 'LAI', 'NFT3S', 'OP3L', 'AAPL3S', 'OP3S',
'A8', 'XDC', 'AIMBOT', 'TOWNS', 'FXS', 'XAUT', 'FFT', 'AGIXT', 'ABI', 'AIOS',
'ANGEL', 'HANEP', 'LIMBO', 'LISTEN', 'MOMO', 'NTH', 'OWL', 'SLVN', 'STEALTH', 'TOLY',
'VOB', 'WAGMEME', 'WORM', 'XCH', 'AMPED', 'REFACTA', 'BLT', 'UNILAPSE', 'DEGENFI', 'NAM',
'GHT', 'LYUM', 'GXAI', 'EMRLD', 'FURI', 'TRUMP404', 'CROWN2', 'FNTIO', 'DOBO', 'OBORTECH',
'BILLIONVIEW', 'GVA', 'HONOR', 'TOKABU', 'OKM', 'MRMINT', 'MONR', 'CELDATA', 'RKFI', 'DREYAI',
'SOEX', 'ETHEREX', 'NND', 'B1OAI', 'GTCAI', 'XWGT', 'STAU', 'PHYCHAIN', 'ZRA', 'MINX',
'OPEN', 'GGC', 'PKAM', 'FUTURE', 'AIHI', 'TONNY', 'BOSS', 'LUNCH', 'COCK', 'AIMINT',
'XIN', 'ASSETMINT', 'KARAT', 'SRC', 'BNA', 'SHIBBABY', 'POKE', 'HYB', 'SECU', 'DEFX',
'UWON', 'PS', 'CKY', 'YAPYO', 'MMON', 'GFM', 'FAVE', 'NZC', 'BDT', 'DRAGON404',
'ESCG', 'DRN', 'XU3O8', 'DIKO', 'GRAND', 'QZN', 'CLX', 'BACHI', 'DELULU', 'DORAFACTORY',
'GBCK', 'SCOT', 'DIGIGOAL', 'LUNAI', 'CVN', 'LUNARBITS', 'JUNE', 'GVL', 'NOW', 'HELI',
'LINKE', 'OMNILABS', 'DARKSTAR', 'DARKECLIPSE', 'SAFE4', 'TUNA', 'TWIF', 'PVT', 'NLINK', 'SUP1',
'RKNE', 'DIVI', 'MMD', 'SVM', 'GAMEVIRTUAL', 'NRWA', 'EIN', 'USDF', 'REDBIRD', 'TAA',
'IN', 'PBT', 'PIKABOSS', 'PULSE', 'SENT', 'AISPF', 'FRT', 'TDS', 'LITAS', 'HKTM',
'XCX', 'GRAMPUS'
);